using System.Text.Json;
using System.Text.Json.Nodes;
using MoniMS.Core.Desktop;
using MoniMS.Core.Presets;
using MoniMS.Core.Shell;
using MoniMS.Core.Shell.Apps;

namespace MoniMS.Core.Tests;

public sealed class AppThemeTests : IDisposable
{
    /// <summary>Gruvbox Material 패키지의 Terminal/settings.json을 줄인 것 (주석·후행 쉼표 포함).</summary>
    public const string TerminalSource = """
        {
            // shared settings
            "$schema": "https://aka.ms/terminal-profiles-schema",
            "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
            "keybindings": [ { "id": "Terminal.FindText", "keys": "ctrl+shift+f" } ],
            "profiles": {
                "defaults": {
                    "colorScheme": "Gruvbox Material",
                    "font": { "face": "JetBrainsMono Nerd Font" },
                    "opacity": 80,
                    "padding": "15",
                    "useAcrylic": true,
                    "antialiasingMode": "cleartype"
                },
                "list": [ { "name": "PowerShell", "colorScheme": "Gruvbox Material", "opacity": 95 } ]
            },
            "schemes": [
                { "name": "Gruvbox Material", "background": "#272E33", "foreground": "#D3C6AA", "black": "#475258" },
                { "name": "Monochrome", "background": "#18181B", "foreground": "#FFFFFF", "black": "#18181B" },
            ],
            "theme": "system",
            "themes": [ { "name": "Monochrome", "tab": { "background": "#18181BFF" } } ],
            "useAcrylicInTabRow": true
        }
        """;

    private const string UserTerminalSettings = """
        // This file was initially generated by Windows Terminal
        {
            "$schema": "https://aka.ms/terminal-profiles-schema",
            "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
            "actions": [ { "command": "paste", "keys": "ctrl+v" } ],
            "profiles": [
                { "name": "Windows PowerShell", "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}" },
                { "name": "Ubuntu", "colorScheme": "Campbell" }
            ],
            "schemes": [
                { "name": "gruvbox material", "background": "#000000", "foreground": "#111111", "black": "#222222" },
                { "name": "My Scheme", "background": "#010101", "foreground": "#020202", "black": "#030303" }
            ]
        }
        """;

    private readonly string _root = Path.Combine(Path.GetTempPath(), "moniMS-apps-" + Guid.NewGuid().ToString("N"));

    public AppThemeTests() => Directory.CreateDirectory(_root);

    public void Dispose()
    {
        if (Directory.Exists(_root))
            Directory.Delete(_root, true);
    }

    private static JsonObject Parse(string text) => (JsonObject)JsonText.Parse(text)!;

    private static IEnumerable<string?> SchemeNames(JsonObject o) =>
        ((JsonArray)o["schemes"]!).Select(s => s!["name"]!.GetValue<string>());

    // ---------- Windows Terminal ----------

    [Fact]
    public void Terminal_merge_keeps_personal_settings_and_replaces_schemes_by_name()
    {
        var target = Parse(UserTerminalSettings);
        var source = WindowsTerminalThemer.Normalize(Parse(TerminalSource))!;
        var warnings = new List<string>();

        WindowsTerminalThemer.Merge(target, source, _ => true, warnings);

        // 같은 이름(대소문자 무시)은 교체, 내 구성표는 유지, 새 구성표는 추가
        Assert.Equal(["Gruvbox Material", "My Scheme", "Monochrome"], SchemeNames(target));
        Assert.Equal("#272E33", target["schemes"]![0]!["background"]!.GetValue<string>());

        // 개인 설정은 그대로, 패키지의 기본 프로필/단축키는 가져오지 않음
        Assert.Equal("{61c54bbd-c2c6-5271-96e7-009a87ff44bf}", target["defaultProfile"]!.GetValue<string>());
        Assert.NotNull(target["actions"]);
        Assert.Null(target["keybindings"]);

        // 예전 배열 형식 profiles → { defaults, list }
        var profiles = (JsonObject)target["profiles"]!;
        Assert.Equal(2, ((JsonArray)profiles["list"]!).Count);
        var defaults = (JsonObject)profiles["defaults"]!;
        Assert.Equal("Gruvbox Material", defaults["colorScheme"]!.GetValue<string>());
        Assert.Equal(80, defaults["opacity"]!.GetValue<int>());
        Assert.Equal("JetBrainsMono Nerd Font", defaults["font"]!["face"]!.GetValue<string>());
        Assert.Null(defaults["antialiasingMode"]); // 모양 화이트리스트 밖

        // 정의된 창 테마가 아니면 theme은 건드리지 않음, 탭 줄 아크릴은 가져옴
        Assert.Null(target["theme"]);
        Assert.True(target["useAcrylicInTabRow"]!.GetValue<bool>());
        Assert.Single(target["themes"]!.AsArray());

        // Ubuntu는 자기 구성표가 있어 바뀌지 않음 → 알림
        Assert.Contains(warnings, w => w.Contains("Ubuntu"));
    }

    [Fact]
    public void Terminal_merge_skips_missing_font_but_keeps_my_font_size()
    {
        var target = Parse("""{ "profiles": { "defaults": { "font": { "face": "Cascadia Mono", "size": 13 } }, "list": [] } }""");
        var source = WindowsTerminalThemer.Normalize(Parse(TerminalSource))!;
        var warnings = new List<string>();

        WindowsTerminalThemer.Merge(target, source, _ => false, warnings);

        var font = target["profiles"]!["defaults"]!["font"]!;
        Assert.Equal("Cascadia Mono", font["face"]!.GetValue<string>());
        Assert.Equal(13, font["size"]!.GetValue<int>());
        Assert.Contains(warnings, w => w.Contains("JetBrainsMono Nerd Font"));
    }

    [Fact]
    public void Terminal_single_scheme_file_is_accepted_and_other_json_is_not()
    {
        var single = WindowsTerminalThemer.Normalize(Parse(
            """{ "name": "Dracula", "background": "#282A36", "foreground": "#F8F8F2", "black": "#21222C" }"""));
        Assert.NotNull(single);
        Assert.Equal("Dracula", WindowsTerminalThemer.PreferredScheme(single!));
        Assert.Equal("color scheme 'Dracula'", WindowsTerminalThemer.Summarize(single!));

        Assert.Null(WindowsTerminalThemer.Normalize(Parse("""{ "profiles": { "list": [] } }""")));
        Assert.Null(WindowsTerminalThemer.Normalize(Parse("""{ "bar": { "height": 30 } }"""))); // komorebi.json 같은 것
    }

    // ---------- Discord ----------

    [Theory]
    [InlineData("Discord/system24.theme.css", true)]
    [InlineData("themes/cool.theme.css", true)]
    [InlineData("Discord/extra.css", true)]
    [InlineData("Spicetify/Themes/TUI/user.css", false)]
    public void Detects_discord_themes(string relative, bool expected)
    {
        var file = Path.Combine(_root, relative);
        Directory.CreateDirectory(Path.GetDirectoryName(file)!);
        File.WriteAllText(file, "body {}");
        Assert.Equal(expected, DiscordThemer.LooksLikeDiscordTheme(relative, file));
    }

    [Fact]
    public void Reads_discord_theme_name_and_fonts()
    {
        var file = Path.Combine(_root, "t.theme.css");
        File.WriteAllText(file, "/**\n * @name system24 (Gruvbox Material) V1\n * @author x\n*/\nbody { --font: 'DM Mono'; --code-font: 'DM Mono'; --x: ''; }");
        Assert.Equal("system24 (Gruvbox Material) V1", DiscordThemer.ReadThemeName(file));
        Assert.Equal(["DM Mono"], DiscordThemer.ReadFonts(file));
    }

    // ---------- 적용 → 복원 (임시 폴더를 %LOCALAPPDATA% / %APPDATA% 로 사용) ----------

    [Fact]
    public async Task Applies_terminal_and_discord_then_restores_exactly()
    {
        var local = Path.Combine(_root, "Local");
        var roaming = Path.Combine(_root, "Roaming");

        // Terminal: 스토어 버전은 기존 설정 있음, Preview는 아직 한 번도 안 켬
        var stable = Path.Combine(local, "Packages", "Microsoft.WindowsTerminal_8wekyb3d8bbwe", "LocalState", "settings.json");
        var preview = Path.Combine(local, "Packages", "Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe", "LocalState", "settings.json");
        Directory.CreateDirectory(Path.GetDirectoryName(stable)!);
        Directory.CreateDirectory(Path.Combine(local, "Packages", "Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe"));
        File.WriteAllText(stable, UserTerminalSettings);

        // Discord: Vencord(설정 있음) + BetterDiscord(설치 직후)
        var vencordSettings = Path.Combine(roaming, "Vencord", "settings", "settings.json");
        Directory.CreateDirectory(Path.GetDirectoryName(vencordSettings)!);
        const string vencordOriginal = """{ "plugins": { "x": { "enabled": true } }, "enabledThemes": ["mine.css"] }""";
        File.WriteAllText(vencordSettings, vencordOriginal);
        Directory.CreateDirectory(Path.Combine(roaming, "BetterDiscord"));

        var library = new ThemeLibrary(Path.Combine(_root, "lib"));
        var package = await new ThemeImporter(library).ImportAsync(MakePackage());
        Assert.Equal(2, package.Apps.Count);

        var storage = new ShellThemeTests.FakeStorage();
        var targets = new AppThemeTargets(local, roaming, _ => true);
        var applier = new ThemeApplier(storage, new ShellThemeTests.DirectWriter(storage), new ShellThemeTests.NoWallpaper(), library,
            targets: targets);

        var result = applier.Apply(package, new ThemeApplyOptions([], false, null, [AppThemeKind.WindowsTerminal, AppThemeKind.Discord]));

        Assert.Empty(result.AppliedMods);
        Assert.Contains("Windows Terminal", result.Apps);
        Assert.Contains("Discord (Vencord, BetterDiscord)", result.Apps);

        var stableNow = Parse(File.ReadAllText(stable));
        Assert.Equal("Gruvbox Material", stableNow["profiles"]!["defaults"]!["colorScheme"]!.GetValue<string>());
        Assert.True(File.Exists(preview));

        Assert.True(File.Exists(Path.Combine(roaming, "Vencord", "themes", "sample.theme.css")));
        var enabled = Parse(File.ReadAllText(vencordSettings))["enabledThemes"]!.AsArray().Select(e => e!.GetValue<string>());
        Assert.Equal(["mine.css", "sample.theme.css"], enabled);
        Assert.True(Parse(File.ReadAllText(vencordSettings))["plugins"]!["x"]!["enabled"]!.GetValue<bool>());
        var bdState = Path.Combine(roaming, "BetterDiscord", "data", "stable", "themes.json");
        Assert.True(Parse(File.ReadAllText(bdState))["Sample Theme"]!.GetValue<bool>());

        Assert.True(applier.HasBackup);
        var restored = applier.RestoreLatest();
        Assert.Equal(["Discord", "Windows Terminal"], restored.Order());

        // 원래 있던 파일은 글자 하나까지 그대로, 없던 파일은 삭제
        Assert.Equal(UserTerminalSettings, File.ReadAllText(stable));
        Assert.Equal(vencordOriginal, File.ReadAllText(vencordSettings));
        Assert.False(File.Exists(preview));
        Assert.False(File.Exists(Path.Combine(roaming, "Vencord", "themes", "sample.theme.css")));
        Assert.False(File.Exists(bdState));
        Assert.False(applier.HasBackup);
    }

    [Fact]
    public async Task Missing_apps_are_skipped_with_a_warning_and_no_backup()
    {
        var library = new ThemeLibrary(Path.Combine(_root, "lib"));
        var package = await new ThemeImporter(library).ImportAsync(MakePackage());
        var storage = new ShellThemeTests.FakeStorage();
        var applier = new ThemeApplier(storage, new ShellThemeTests.DirectWriter(storage), new ShellThemeTests.NoWallpaper(), library,
            targets: new AppThemeTargets(Path.Combine(_root, "none-l"), Path.Combine(_root, "none-r"), _ => true));

        var result = applier.Apply(package, new ThemeApplyOptions([], false, null, [AppThemeKind.WindowsTerminal, AppThemeKind.Discord]));

        Assert.Empty(result.Apps);
        Assert.Contains(result.Warnings, w => w.Contains("Windows Terminal is not installed"));
        Assert.Contains(result.Warnings, w => w.Contains("Vencord"));
        Assert.False(applier.HasBackup);
    }

    [Fact]
    public async Task Old_manifest_is_rescanned_for_app_themes()
    {
        var library = new ThemeLibrary(Path.Combine(_root, "lib"));
        var package = await new ThemeImporter(library).ImportAsync(MakePackage());

        // 예전 버전이 저장한 매니페스트 흉내: schemaVersion 1, apps 없음
        var manifest = Path.Combine(package.Directory, "theme.json");
        var json = JsonNode.Parse(File.ReadAllText(manifest))!.AsObject();
        json["schemaVersion"] = 1;
        json.Remove("apps");
        File.WriteAllText(manifest, json.ToJsonString());

        var loaded = Assert.Single(library.GetAll());
        Assert.Equal(2, loaded.Apps.Count);
        Assert.Equal(ThemePackage.CurrentSchemaVersion, loaded.SchemaVersion);
        Assert.Contains("\"apps\"", File.ReadAllText(manifest)); // 다시 저장됨
    }

    private sealed class RecordingWallpaper : IWallpaperService
    {
        public string Current { get; set; } = "original.jpg";

        public WallpaperSettings Capture(string d) =>
            new() { Monitors = [new MonitorWallpaper { ImageFile = Current }] };

        public void Apply(WallpaperSettings s, string d) => Current = s.Monitors[0].ImageFile!;
        public void SetForAllMonitors(string p, WallpaperPosition pos) => Current = Path.GetFileName(p);
    }

    [Fact]
    public async Task Reset_to_original_undoes_every_apply_at_once()
    {
        var local = Path.Combine(_root, "Local");
        var stable = Path.Combine(local, "Packages", "Microsoft.WindowsTerminal_8wekyb3d8bbwe", "LocalState", "settings.json");
        Directory.CreateDirectory(Path.GetDirectoryName(stable)!);
        File.WriteAllText(stable, UserTerminalSettings);

        var library = new ThemeLibrary(Path.Combine(_root, "lib"));
        var package = await new ThemeImporter(library).ImportAsync(MakePackage());
        Directory.CreateDirectory(Path.Combine(package.FilesDirectory, "wallpapers"));
        var wp = Path.Combine("wallpapers", "theme.png");
        File.WriteAllText(package.FullPath(wp), "png");

        var storage = new ShellThemeTests.FakeStorage();
        var wallpaper = new RecordingWallpaper();
        var applier = new ThemeApplier(storage, new ShellThemeTests.DirectWriter(storage), wallpaper, library,
            targets: new AppThemeTargets(local, Path.Combine(_root, "Roaming"), _ => true));
        Assert.False(applier.HasOriginal);

        // 테마를 두 번 적용: 두 번째 백업에는 "첫 테마가 적용된 상태"가 들어간다
        var options = new ThemeApplyOptions([WindhawkMods.TaskbarStyler], false, null, [AppThemeKind.WindowsTerminal]);
        package.Mods.Add(new ThemeModConfig { ModId = WindhawkMods.TaskbarStyler, SourceFile = "taskbar.json" });
        File.WriteAllText(package.FullPath("taskbar.json"), """{ "theme": "", "controlStyles[0].target": "Taskbar.TaskbarFrame" }""");
        applier.Apply(package, options);
        Assert.Equal("Taskbar.TaskbarFrame", storage.Mods[WindhawkMods.TaskbarStyler]["controlStyles[0].target"]);
        Thread.Sleep(5);
        applier.Apply(package, options);
        Assert.True(applier.ApplyWallpaper(package, wp));
        Assert.True(applier.ApplyWallpaper(package, wp)); // 두 번째는 원래 배경화면을 덮어쓰지 않아야 함
        Assert.Equal("theme.png", wallpaper.Current);
        Assert.True(applier.HasOriginal);

        var restored = applier.ResetToOriginal();
        Assert.True(applier.RestoreOriginalWallpaper());

        Assert.Equal(UserTerminalSettings, File.ReadAllText(stable)); // 첫 적용 전 내용
        Assert.Equal("1", Assert.Single(storage.Mods[WindhawkMods.TaskbarStyler]).Value); // 첫 적용 전 값 {old: "1"}
        Assert.Contains("Windows Terminal", restored);
        Assert.Equal("original.jpg", wallpaper.Current);
        Assert.False(applier.HasBackup);
        Assert.False(applier.HasOriginal);
    }

    private string MakePackage()
    {
        var dir = Path.Combine(_root, "MyPack");
        Directory.CreateDirectory(Path.Combine(dir, "Terminal"));
        Directory.CreateDirectory(Path.Combine(dir, "Discord"));
        File.WriteAllText(Path.Combine(dir, "Terminal", "settings.json"), TerminalSource);
        File.WriteAllText(Path.Combine(dir, "Discord", "sample.theme.css"), "/**\n * @name Sample Theme\n */\nbody { color: red; }");
        return dir;
    }
}
